apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: utjtahens-go 
  janus-idp.io/tekton: utjtahens-go
  backstage.io/kubernetes-id: utjtahens-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: utjtahens-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml